export const events = [
  {
    id: "french-kiss-night",
    slug: "french-kiss-night",
    title: "French Kiss Night",
    date: "April 4, 2026",
    time: "10:00 PM – 4:00 AM",
    startDateISO: "2026-04-04T22:00:00+08:00",
    endDateISO: "2026-04-05T04:00:00+08:00",
    venue: "The Stratosphere — 4/F Century City Mall, Makati",
    venueName: "The Stratosphere",
    venueAddress: "4/F Century City Mall, Amorsolo Drive, Makati",
    category: "Gala",
    price: "₱1,500",
    priceAmount: 1500,
    currency: "PHP",
    paddlePriceId: import.meta.env.VITE_PADDLE_PRICE_FRENCH_KISS ?? "",
    image: "/images/french-kiss.png",
    description: "An exclusive evening of French-inspired glamour, live music, premium cocktails, and unmatched Makati nightlife energy.",
    ticketLink: "https://celeweevent.com/event/french-kiss-night/#tribe-tickets__tickets-form",
    sold_out: false
  },
  {
    id: "nuit-blanche",
    slug: "nuit-blanche",
    title: "Nuit Blanche",
    date: "May 15, 2026",
    time: "9:00 PM – 3:00 AM",
    startDateISO: "2026-05-15T21:00:00+08:00",
    endDateISO: "2026-05-16T03:00:00+08:00",
    venue: "Aura Premier, BGC, Taguig",
    venueName: "Aura Premier",
    venueAddress: "Upper McKinley Road, Bonifacio Global City, Taguig",
    category: "Private",
    price: "₱2,000",
    priceAmount: 2000,
    currency: "PHP",
    paddlePriceId: import.meta.env.VITE_PADDLE_PRICE_NUIT_BLANCHE ?? "",
    image: "/images/nuit-blanche.png",
    description: "An all-white affair at one of BGC's most iconic venues. Strict dress code: all white attire required.",
    ticketLink: "#",
    sold_out: false
  },
  {
    id: "crimson-masquerade",
    slug: "crimson-masquerade",
    title: "Crimson Masquerade",
    date: "June 21, 2026",
    time: "10:00 PM – 5:00 AM",
    startDateISO: "2026-06-21T22:00:00+08:00",
    endDateISO: "2026-06-22T05:00:00+08:00",
    venue: "Sofitel Philippine Plaza, Pasay",
    venueName: "Sofitel Philippine Plaza Manila",
    venueAddress: "CCP Complex, Roxas Boulevard, Pasay, Metro Manila",
    category: "VIP",
    price: "₱3,500",
    priceAmount: 3500,
    currency: "PHP",
    paddlePriceId: import.meta.env.VITE_PADDLE_PRICE_CRIMSON_MASQUERADE ?? "",
    image: "/images/crimson-masquerade.png",
    description: "A masquerade ball for Manila's VIP circle — with live performers, bespoke cocktails, and mystery at every turn.",
    ticketLink: "#",
    sold_out: false
  }
];
